name = "p"
main = "src/index.ts"
compatibility_date = "2022-05-30"

kv_namespaces = [
    { binding = "PASTE_STORAGE", id = "your_kv_id", preview_id = "your_preview_kv_id" }
]

[build]
command = "node build.js"
