name = "p"
main = "src/index.ts"
compatibility_date = "2022-05-30"

[build]
command = "node build.js"

[env.dev]
kv_namespaces = [
    { binding = "PASTE_STORAGE", id = "your_kv_preview_id", preview_id = "your_kv_preview_id" }
]

[env.production]
kv_namespaces = [
    { binding = "PASTE_STORAGE", id = "your_kv_id" }
]
